# Generated by Django 4.1.7 on 2024-03-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=100)),
                ('prime', models.IntegerField(blank=True, null=True)),
                ('dealership', models.CharField(max_length=100)),
            ],
        ),
    ]
